name: 2. merge-main

on:
  push:
    branches: [ master, main ]
  # pull_request:
  #   branches: [ master, main ]

env:
  JAVA_VERSION: 17

jobs:
  # Skipping workflow: add '[skip ci]' string in commit message
  # Ref: https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs

  pmd-java-maven:
    uses: bvilela/github-actions-workflows/.github/workflows/pmd-java-maven.yml@feature/add-reusable-workflows

  ci-java-maven:
    needs: pmd-java-maven
    uses: bvilela/github-actions-workflows/.github/workflows/ci-java-maven.yml@feature/add-reusable-workflows
    with:
      java-version: $JAVA_VERSION
      maven-settings-file: maven-settings.xml

  sonarcloud-java-maven:
    needs: ci-java-maven
    uses: bvilela/github-actions-workflows/.github/workflows/sonarcloud-java-maven.yml@feature/add-reusable-workflows
    with:
      projectKey: bvilela_list-builder
      java-version: $JAVA_VERSION
    secrets: inherit
