name: 3.ci

on:
  push:
    branches: [ master, main ]

jobs:
  # Skipping workflow: add '[skip ci]' string in commit message
  # Ref: https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs

  pmd-java-maven:
    uses: bvilela/github-actions-workflows/.github/workflows/pmd-java-maven.yml@v0.2.0

  ci-java-maven:
    needs: pmd-java-maven
    uses: bvilela/github-actions-workflows/.github/workflows/ci-java-maven.yml@v0.2.0
    with:
      java_version: 17
      maven_settings_file: maven-settings.xml
    secrets: inherit

  sonarcloud-java-maven:
    needs: ci-java-maven
    uses: bvilela/github-actions-workflows/.github/workflows/sonarcloud-java-maven.yml@v0.2.0
    with:
      java_version: 17
      projectKey: bvilela_list-builder
    secrets: inherit
