name: 4.cd

on:
  release:
    types: [created]

jobs:
  # Skipping workflow: add '[skip ci]' string in commit message
  # Ref: https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs
 
  cd-java-maven:
    uses: bvilela/github-actions-workflows/.github/workflows/cd-java-maven.yml@v0.2.0
    with:
      java_version: 17
      maven_settings_file: maven-settings.xml
    secrets: inherit
